//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashAdvanceMvC.Models.LogEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbCashAdvance
    {
        public int Id { get; set; }
        public string requestBy { get; set; }
        public string requestDate { get; set; }
        public string approvedDate { get; set; }
        public string approvedBY { get; set; }
        public string requestStatus { get; set; }
        public int Employee_Id { get; set; }
        public string amount { get; set; }
        public string department { get; set; }
    }
}
